name: ocn-tools
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - cartopy
  - hvplot
  - arviz
  - metpy
  - pandas>=2
  - xarray>=2023
  - zarr
  - dask
  - netCDF4
  - bottleneck
  - scipy
  - pyinterp
  - xrft
  - numpy_groupies
  - xesmf>=0.7.0
  - pint-xarray
  - gcm_filters
  - pytest
  - dvc
  - tqdm
  - brotlipy
  - cmocean
  - jupyter-book
  - ghp-import
  - pip:
      - hydra-core
      - pyrootutils
      - loguru
      - xrpatcher
      - autoroot
      - einops
      - corner
