defaults:
  run:
    shell: bash -l {0}
name: PyTest
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.3.1-0"
          environment-file: environment.yaml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: "all"
      - name: install xarray-dataclasses
        run: pip install --no-deps xarray-dataclasses
        shell: micromamba-shell {0}
      - name: pytest
        run: pytest --version
        shell: micromamba-shell {0}
