defaults:
  run:
    shell: bash -l {0}
name: PyTest
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3.5.2
      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "1.4.5-0"
          environment-file: environment.yaml
          init-shell: bash
          cache-environment: true
          post-cleanup: "all"
      - name: install xarray-dataclasses
        run: pip install --no-deps xarray-dataclasses
        shell: micromamba-shell {0}
      - name: pytest
        run: pytest ocn_tools/_src
        shell: micromamba-shell {0}
